# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Echo tests
        run: echo "$HOME workld"

      - name: HB tests
        run: |
          VERSION=$(echo $GITHUB_REF_NAME | cut -c 2-)
          FILE=".github/workflows/blank.yml"
          cat $FILE
          MAC_ARM_URL="https://github.com/${{ github.repository }}/releases/download/${VERSION}/dips-${VERSION}-aarch64-apple-darwin.tar.gz"
          MAC_ARM_SHA256=$(echo "dips-${VERSION}-aarch64-apple-darwin.tar.gz.sha256" | awk '{ print $1 }')
          echo "$MAC_ARM_URL"
          echo "$VERSION"
          echo VERSION
          echo "${VERSION}"


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
